{{ config(materialized='source') }}

-- Synthetic wallet-transaction stream for the StarRocks upsert/point-lookup
-- demo (see docs/SR_POC_WALLET_UPSERT_DEMO.md). Not related to the funnel
-- e-commerce demo; a separate, narrow pipeline motivated by an internal PAM
-- Operational Query Layer proposal that argues for StarRocks Primary Key
-- tables to serve upsert-heavy financial reads. All data synthetic --
-- generated by scripts/wallet_producer.py, no real accounts/PII/payments.
--
-- `amount` is `decimal(38,9)`, not `double precision`. Not just a fix for a
-- StarRocks quirk (CTAS coerces DOUBLE/literal-float results to
-- decimal(38,9) unconditionally in this version -- confirmed live
-- 2026-09-12, tried CAST(NULL/0.0/1e0 AS DOUBLE), RAND(), and explicit
-- DOUBLE division, all became decimal(38,9)) -- fixed-point decimal is also
-- the more correct type for monetary amounts in a real financial system
-- anyway, avoiding floating-point precision issues on money.
CREATE SOURCE {{ this }} (
    transaction_id varchar,
    account_id varchar,
    type varchar,
    amount decimal,
    status varchar,
    event_time timestamptz,
    WATERMARK FOR event_time AS event_time - INTERVAL '5' SECOND
) WITH (
    connector = 'kafka',
    topic = 'wallet_transactions',
    properties.bootstrap.server = 'redpanda:9092',
    scan.startup.mode = 'earliest'
) FORMAT PLAIN ENCODE JSON
