slice_name: "Funnel Over Time (Live - Zero-Copy) \u2014 Last Hour [RisingWave, via\
  \ StarRocks \u2014 always queries Databricks needlessly]"
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_line
params:
  datasource: 4__table
  viz_type: echarts_timeseries_line
  groupby: []
  metrics:
  - sum__viewers
  - sum__carters
  - sum__purchasers
  granularity_sqla: window_start
  time_range: '1 hour ago : now'
  adhoc_filters:
  - clause: WHERE
    subject: window_start
    operator: TEMPORAL_RANGE
    comparator: '1 hour ago : now'
    expressionType: SIMPLE
  order_desc: false
  x_axis: window_start
  x_axis_time_format: '%H:%M'
  y_axis_format: SMART_NUMBER
  rich_tooltip: true
  show_legend: true
  row_limit: 10000
  annotation_layers: []
query_context: null
cache_timeout: null
uuid: 45f66882-8284-44f0-8563-10ba1c19c078
version: 1.0.0
dataset_uuid: 3f6ad042-8ef6-4bf3-9c05-7405652112ef
